name: login_demo
description: A new Flutter application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_auth_buttons: ^0.10.0
  expandable: ^4.1.4
  readmore: ^1.0.1
  flutter_bloc: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
    - family: Alegreya Sans
      fonts:
        - asset: fonts/AlegreyaSans-Black.ttf




  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
